[package]
name = "azur_lane_data_collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azur_lane = { path = "../azur_lane" }
simd-json = { version = "0.13.10", features = ["serde"] }
once_cell = "1.19.0"

[dependencies.clap]
version = "4.5.4"
features = ["derive"]

[dependencies.mlua]
version = "0.9.7"
features = ["lua54", "vendored"]

[dependencies.serde]
version = "1.0.197"
features = ["rc", "derive"]
