[package]
name = "azur_lane_data_collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azur_lane = { path = "../azur_lane" }
serde_json = "1.0.116"
once_cell = "1.19.0"
anyhow = "1.0.82"
image = "0.24.9"

unity_rs = { git = "https://github.com/yuanyan3060/unity-rs.git", rev = "428d47f" }

[dependencies.clap]
version = "4.5.4"
features = ["derive"]

[dependencies.mlua]
version = "0.9.7"
# luajit is not supported because the game scripts have an absurd amount of constants
features = ["lua54", "vendored"]

[dependencies.serde]
version = "1.0.197"
features = ["rc", "derive"]
