[package]
name = "utils"
version = "1.1.0"
edition = "2021"
rust-version = "1.80"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
bitflags = "2.6.0"
chrono = "0.4.38"
